### ISSUE TITLE
如何将图片上传到自己的imgur 账号下？

### ISSUE THREAD

**Issue by zen010101** [addozhang/obsidian-image-upload-toolkit#10]
How to upload images to my account of the Imgur ?

**Comment by addozhang** [comment]
@zen010101 configure your own "Client ID" here.

![2024-01-08 at 08 57 12](https://github.com/addozhang/obsidian-image-upload-toolkit/assets/2224492/04948ba1-bcff-412f-99b3-a037f1183252)
