### ISSUE TITLE
FR: add ImageKit endpoints as upload target

### ISSUE THREAD

**Issue by andrey-jef** [addozhang/obsidian-image-upload-toolkit#12]
Hi,

This is a Feature Request.

[imageKit](https://imagekit.io/) is an alternative of [cloudinary](https://cloudinary.com).

Do you think it's feasible to add ImageKit as an upload target?

I read their [Upload File API](https://docs.imagekit.io/api-reference/upload-file-api/secure-client-side-file-upload) but still not figure out how to translate these info into a feasible config code.

Thanks

**Comment by addozhang** [comment]
@andrey-jef Please try with 0.5.0 which supporting imageKit now.

**Comment by andrey-jef** [comment]
> @andrey-jef Please try with 0.5.0 which supporting imageKit now.

Hi @addozhang 

Thank you so much. It works.

Could you please also add a parameter to specify the destination folder in imagekit library, where the local image will be uploaded to?

With the current version of plugin (0.5), the uploaded image is sent directly to `Files` section in ImageKit. I can manually move each files to a specific folder. But if the plugin has an option to do so, will be much more convenient.

**Comment by addozhang** [comment]
@andrey-jef Got it and 0.5.1 released. You can specify folder name in setting panel now.

**Comment by andrey-jef** [comment]
Thank you for your time investigating the docs and implementing this feature. It works flawlessly on my Win pc.
