### ISSUE TITLE
Q&A: Usage of command `Publish Page`

### ISSUE THREAD

**Issue by andrey-jef** [addozhang/obsidian-image-upload-toolkit#13]
Hi,

I want to clarify the behavior of command `Image Upload Toolkit: Publish Page`.

When typing the command `Image Upload Toolkit: Publish Page`, the plugin will "upload all local images in the Obsidian vault to remote storage" or only "upload all local images which are used in the current note to remote storage"?

**Comment by addozhang** [comment]
"upload all local images which are used in the current note to remote storage" is correct.
