### ISSUE TITLE
无法上传到阿里云OSS

### ISSUE THREAD

**Issue by sanwacompany** [addozhang/obsidian-image-upload-toolkit#18]
我用publish page命令一直不成功，如图所示，提示can not locate xxxxxxx
![image](https://github.com/user-attachments/assets/8080a82a-34a6-4763-bd95-80726c080611)

**图片在md文件同级的images目录下**
![image](https://github.com/user-attachments/assets/6984f2e4-3eac-4701-9ecb-8d388046c25e)

**我的设置如下图所示**
![image](https://github.com/user-attachments/assets/a78ed037-8726-4299-a3d1-45a3c839c0d9)

**Comment by addozhang** [comment]
这里的 Attachment Location 与“settings/files and links” 中的 Attachment folder path 是一个意思，就是图片放在独立的目录中，而不是与 md 文件同级目录。

实际上你将 md 文件同级目录中的图片，放到 Attachment folder path 中一样可以在 md 文件中展示（语法和路径不变）。

![2024-09-10 at 06 52 05](https://github.com/user-attachments/assets/6a91f0a1-35d7-48b0-856d-9fb87cdb902e)

**Comment by jonselesile** [comment]
大佬，我在上传md文件夹（叫做web）内单独创建了个assets文件夹用来存储这些md文件的图片附件，然后Attachment Location设置的路径就是web-clipper/assets，也没有报错，但是用publish page命令也会出现楼主一模一样的情况

**Comment by addozhang** [comment]
@jonselesile 方便发下目录结构的截图么？还有报错信息。

**Comment by jonselesile** [comment]
好的好的
![PixPin_2025-01-08_12-02-10](https://github.com/user-attachments/assets/af25ce02-7df9-48b4-877f-c619f12d47e6)
![PixPin_2025-01-08_12-01-33](https://github.com/user-attachments/assets/d0c20e38-3222-434b-a975-a1b04da51add)

**Comment by jonselesile** [comment]
请问大佬有空方便解答一下不

**Comment by addozhang** [comment]
请问你 markdown 中用的图片路径是什么？

**Comment by jonselesile** [comment]
![](1736264383-390fcf8f19cff1e7f4be99b8eac2dcca.png)，就是直接使用assets里的图片

**Comment by addozhang** [comment]
> 这里的 Attachment Location 与“settings/files and links” 中的 Attachment folder path 是一个意思，就是图片放在独立的目录中，而不是与 md 文件同级目录。
> 
> 实际上你将 md 文件同级目录中的图片，放到 Attachment folder path 中一样可以在 md 文件中展示（语法和路径不变）。
> 
> ![2024-09-10 at 06 52 05](https://private-user-images.githubusercontent.com/2224492/365836800-6a91f0a1-35d7-48b0-856d-9fb87cdb902e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NDg0MjMsIm5iZiI6MTczNjk0ODEyMywicGF0aCI6Ii8yMjI0NDkyLzM2NTgzNjgwMC02YTkxZjBhMS0zNWQ3LTQ4YjAtODU2ZC05ZmI4N2NkYjkwMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTMzNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVjZmIwNWRmODdiYTc0ODA0NWJkOWE4OTIxZTMwY2FmZTYyYjJhODY5YjY4YmIxZTYzN2Q5YzVmZWM5MjM0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.d4hu5mJJ0u8EvFogovoe5dz1KiwXuNbrH5fnnyqSEAk)

@jonselesile 参考这个

**Comment by JasonCL2015** [comment]
![Image](https://github.com/user-attachments/assets/f8c3db41-0e84-447e-a3a7-3bb0e69bad53)

![Image](https://github.com/user-attachments/assets/48fbffb8-4122-4cfb-8f19-ce8b47e75e62)
这两个地方一样就行
