### ISSUE TITLE
ali oss 支持指定目录

### ISSUE THREAD

**Issue by atlas555** [addozhang/obsidian-image-upload-toolkit#4]
ali oss 支持指定目录

**Comment by addozhang** [comment]
请问是想自定义图片保存在 bucket 中的目录么？比如 /2023/02/09/pic.jpg

**Comment by atlas555** [comment]
> 请问是想自定义图片保存在 bucket 中的目录么？比如 /2023/02/09/pic.jpg

是的，我现在使用 vs 写 md，其中图片是上传到指定 oss 目录，类似media/2023/xxx.jpg 的方式。现在 ob 插件只到根目录，不利用上传文件的管理

**Comment by addozhang** [comment]
刚发布了 0.3.0，可以试试。

**Comment by atlas555** [comment]
> 刚发布了 0.3.0，可以试试。

已经使用，非常棒👍🏻！ 针对阿里云oss 的图片上传在提两个优化啊
1、若配置自定义域名, 对象url将使用所配置的域名（我的 blog 图片和 blog 主域名一致，阿里云的自有域名不友好）
2、是否启用HTTPS, 若开启, 对象url将使用https协议（图片域名有 https 的，现在上传默认是 http 的）

**Comment by addozhang** [comment]
发布了 0.3.1，因为我没有备案的域名所以无法测试，请帮忙测试下。

关于第二个问题，这个应该是 oss 那边的配置，插件是没有做处理的。
