### ISSUE TITLE
support s3 (and s3 compatible) endpoints as upload target

### ISSUE THREAD

**Issue by wolfspyre** [addozhang/obsidian-image-upload-toolkit#5]
When implementing the upload-to-s3 storage backend, It would be helpful to keep in mind the use-case of S3 COMPATIBLE endpoints. There are nuanced behavioral differences between some of the providers.

It may be that someone wants to have a file deployed/uploaded to multiple locations...  

A contrived use case here might be 'for the environment `prod`, all referenced images should be served from image-storage _"aws-worky_account-us-east" bucket 'prod-img-bucket'   ;  for the environment `integration` images should be served from "aws-worky_account-us-west" bucket 'moarpics' .. and for the environment `localdev` the referenced image should be served from (localstorage,minio docker container backed endpoint, imgur, webdav,  ) 

another contrived use case might be an environment where someone's workflow involves multiple variants of an image/artifact:
say:
 - high resolution, watermarkerd files live here 
 - web-quality images live here
 - raw files live here
or perhaps:
 - draft-stage assets live $`here`.
     - These images are bucketized by `client`/`project`
     - These images are named `ymd`-`clientname`-`projectname`-`image#`
 - pending-approval/in-review-stage assets live $`there`, 
   - They are bucketized by `reviewstate`/`client`/`project` 
   - They are named according to the schema `ymd`-`clientname`-`projectname`-`image#`
- live production-stage assets live $`overthere`
  - They are bucketized by `year`/`month`/`clientproject-hash`
  - they are named `custom-prod-image-abbreviation`-`image#`

granted.... these contrived workflows are heavily unrelated to your toolkit... but I was trying to envision different reasonable circumstance that might leave one wanting the flexibility of saying 'depending on $contextualthing this image may be located [here,there,somewhereelse]' and that if possible, and elegant to implement, your plugin may reduce someone's friction... but it should definitely attempt to not make their workflow HARDER.'

if that makes sense?

**Comment by hooao** [comment]
Any plane to support customized S3 storage?

**Comment by addozhang** [comment]
@hooao just released 0.6.0 to support AWS s3, please have a try.

**Comment by addozhang** [comment]
å
