### ISSUE TITLE
Feature request : 希望增加动态附件路径支持，可以从与当前文件同目录下的assets文件下与文件同名的附件文件夹中获取图片

### ISSUE THREAD

**Issue by martinniee** [addozhang/obsidian-image-upload-toolkit#6]
你好 @addozhang  感谢你创建这个插件，其中 保留本地路径的功能很符合我的需求。但我目前还没有正式使用此插件，因为遇到了一个问题。
不知道是否因为我不熟悉配置，插件设置中针对`imgur`图床服务的设置中附件（图片）的位置似乎只能指定固定某个路径下的文件夹。如果人们选择将库根目录下的某个文件夹作为统一的附件文件夹，那么这个设置就很符合。
![image](https://github.com/addozhang/obsidian-image-upload-toolkit/assets/55736512/4b3112aa-aa93-46dc-99e5-bf1dfc0fb0c5)

可是当前使用obsidian库的配置习惯是——每个文件对应一个附件文件夹，这也就是说，不同文件其附件来自于不同的文件夹（路径）。
这样此插件似乎就无法满足我的需求。是否存在解决办法，比如支持设置 变量规则，比如我的 本地（图片）附件配置如下：

```
foo.md         # markdown文档
assets           # 所在目录的附件文件夹
  |____foo-images      # 与markdown文件对应的附件文件夹
```

可以提供类似 `./assets/${filename}-images` 这样的路径支持，这样可以“动态”的获取当前需上传图片的文档中的图片附件。
![image](https://github.com/addozhang/obsidian-image-upload-toolkit/assets/55736512/fe2c4f41-9727-4e78-bd52-231f7af7dbaf)

或者有什么其他建议，想法也可告诉我。

**Comment by martinniee** [comment]
为什么要多加一个 `assets`文件夹是因为如果所有附件文件夹和 文件在同级目录，这样影响文件列表浏览，所以选择将所有的附件文件夹都“隐藏”在 `assets`目录下。还有为什么选择单独一个文件一个附件文件夹，是因为如果将所有的附件都储存在固定的某个文件夹（比如根目录 `attachments`下），这样不利于管理（虽然也没什么需要管理的😂），还有个人的一些考量😀。

**Comment by addozhang** [comment]
如果使用了子目录中的图片，那文档里的 markdown 语法怎么写？

注，实际使用下来，反而使用单一的附件目录方便文件的复用。

**Comment by martinniee** [comment]
> 如果使用了子目录中的图片，那文档里的 markdown 语法怎么写？
> 
> 注，实际使用下来，反而使用单一的附件目录方便文件的复用。

使用了子目录中的图片会有什么影响吗？我不太懂其中的细节，请告诉我，如果可能的话。obsidian里面图片路径无非就三种类型——最短路径，相对路径，基于库的绝对路径，这几种路径类型，应该都可以获取到图片数据吧。还有你说的“复用”是什么意思

**Comment by martinniee** [comment]
非常抱歉，我对于图床上传相关实现细节并不了解，所以可能存在某些地方我没有考虑进去（想当然了）。不过应该没什么影响吧，统一储存在根目录或者分开存储。
