### ISSUE TITLE
all images upload command

### ISSUE THREAD

**Issue by Andrea-28-03** [addozhang/obsidian-image-upload-toolkit#7]
Hi, really nice plug in but it would be really usefull if it had an all images upload command to do all the images at once and note one page at a time thanks

**Comment by addozhang** [comment]
Sorry, I am not clear with your request. Now it does upload all images at once.

**Comment by Andrea-28-03** [comment]
I meant that before I uploaded all my images, I stored them all locally and now I have a lot of them taking up a lot of space and it would be usefull if there would be a command to upload all off them for the entire vault and not only for one note, thanks

**Comment by addozhang** [comment]
I got it now. I also thought about this solution before. With it, there should be a local index for all uploaded images. At the same time, the index should be updated once the local images change: rename, delete, or update.

It will be a little complicated.

**Comment by Andrea-28-03** [comment]
I thought that it could scrape one by one the entire vault doing each note like it does when you use the command

**Comment by andrey-jef** [comment]
> I got it now. I also thought about this solution before. With it, there should be a local index for all uploaded images. At the same time, the index should be updated once the local images change: rename, delete, or update.
> 
> It will be a little complicated.

Hi,

If you intend to implement this feature, please clearly state in the command name that this command will affect all the notes inside the vault, but not only the current note. 

If the plugin can pop up a dialog to confirm the user's intention (i.e. replace all local image links inside the vault by their remote links) would be awesome.

**Comment by addozhang** [comment]
Sorry, I am not planing to implement this feature. This plugin will work on single note only.
