### ISSUE TITLE
Images which have been resized do not upload to imgur

### ISSUE THREAD

**Issue by Tanzeel159** [addozhang/obsidian-image-upload-toolkit#8]
It doesn't upload images which have been resized for example ![[sample.png|290]] if you have it resized this way, it will simply not upload it and the link doesn't get replaced by imgur link because it didn't upload it.

**Comment by addozhang** [comment]
Yes, it does not cover the resizing case. Will fix it later.

**Comment by addozhang** [comment]
@Tanzeel159 plz try with 0.3.4.
